export const VOCAB_TASKS = {
  "w1-d1-t1": [
    {
      "word": "Representative",
      "meaning": "Người đại diện",
      "romaji": "",
      "hiragana": "",
      "example": "The representative from the sales department will assist you.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280400,
      "lang": "en"
    },
    {
      "word": "Significant",
      "meaning": "Đáng kể, quan trọng",
      "romaji": "",
      "hiragana": "",
      "example": " A significant increase in sales was observed last quarter.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280401,
      "lang": "en"
    },
    {
      "word": "Negotiate",
      "meaning": "Đàm phán, thương lượng",
      "romaji": "",
      "hiragana": "",
      "example": " We need to negotiate the terms of the contract before signing.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280402,
      "lang": "en"
    },
    {
      "word": "Policy",
      "meaning": "Chính sách",
      "romaji": "",
      "hiragana": "",
      "example": " The company's return policy allows customers to return products within 30 days.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280403,
      "lang": "en"
    },
    {
      "word": "Available",
      "meaning": "Có sẵn, rảnh rỗi",
      "romaji": "",
      "hiragana": "",
      "example": " These products are available in our store.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280404,
      "lang": "en"
    },
    {
      "word": "Implement",
      "meaning": "Thi hành, thực hiện",
      "romaji": "",
      "hiragana": "",
      "example": " The company plans to implement the new software next month.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280405,
      "lang": "en"
    },
    {
      "word": "Candidate",
      "meaning": "Ứng viên",
      "romaji": "",
      "hiragana": "",
      "example": " The candidate has an impressive resume and relevant experience.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280406,
      "lang": "en"
    },
    {
      "word": "Exceed",
      "meaning": "Vượt quá, phóng đại",
      "romaji": "",
      "hiragana": "",
      "example": " The sales exceeded our expectations this quarter.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280407,
      "lang": "en"
    },
    {
      "word": "Productivity",
      "meaning": "Năng suất",
      "romaji": "",
      "hiragana": "",
      "example": " Productivity has increased significantly this year.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280408,
      "lang": "en"
    },
    {
      "word": "Promptly",
      "meaning": "Ngay lập tức, đúng giờ",
      "romaji": "",
      "hiragana": "",
      "example": " The meeting started promptly at 9 AM.",
      "katakana": "",
      "type": "adv",
      "ipa": "",
      "key": 1770134280409,
      "lang": "en"
    },
    {
      "word": "Inspection",
      "meaning": "Sự kiểm tra, thanh tra",
      "romaji": "",
      "hiragana": "",
      "example": " The inspection revealed several safety violations.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280410,
      "lang": "en"
    },
    {
      "word": "Merchandise",
      "meaning": "Hàng hóa (thương mại)",
      "romaji": "",
      "hiragana": "",
      "example": " The store offers a wide range of merchandise for customers.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280411,
      "lang": "en"
    },
    {
      "word": "Strictly",
      "meaning": "Một cách nghiêm ngặt",
      "romaji": "",
      "hiragana": "",
      "example": " The company enforces its policies strictly to ensure compliance.",
      "katakana": "",
      "type": "adv",
      "ipa": "",
      "key": 1770134280412,
      "lang": "en"
    },
    {
      "word": "Promote",
      "meaning": "Thăng chức, quảng bá",
      "romaji": "",
      "hiragana": "",
      "example": " The company promotes employees based on their performance and dedication.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280413,
      "lang": "en"
    },
    {
      "word": "Replacement",
      "meaning": "Sự thay thế, người thay thế",
      "romaji": "",
      "hiragana": "",
      "example": " The company has hired a replacement for the vacant position.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280414,
      "lang": "en"
    },
    {
      "word": "Tentative",
      "meaning": "Dự kiến, không chắc chắn",
      "romaji": "",
      "hiragana": "",
      "example": " The tentative schedule is subject to change based on project requirements.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280415,
      "lang": "en"
    },
    {
      "word": "Reimburse",
      "meaning": "Hoàn lại tiền",
      "romaji": "",
      "hiragana": "",
      "example": " Employees will be reimbursed for travel expenses.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280416,
      "lang": "en"
    },
    {
      "word": "Eligible",
      "meaning": "Đủ tư cách, thích hợp",
      "romaji": "",
      "hiragana": "",
      "example": " Employees must meet the eligibility criteria to participate in the program.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280417,
      "lang": "en"
    },
    {
      "word": "Inquiry",
      "meaning": "Câu hỏi, sự thắc mắc",
      "romaji": "",
      "hiragana": "",
      "example": " Customers can contact the inquiry department for more information.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280418,
      "lang": "en"
    },
    {
      "word": "Announce",
      "meaning": "Thông báo, công bố",
      "romaji": "",
      "hiragana": "",
      "example": " The company announced a new product launch next month.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280419,
      "lang": "en"
    },
    {
      "word": "Mandatory",
      "meaning": "Bắt buộc",
      "romaji": "",
      "hiragana": "",
      "example": " Attendance at the training session is mandatory for all employees.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280420,
      "lang": "en"
    },
    {
      "word": "Subscription",
      "meaning": "Sự đăng ký, thuê bao",
      "romaji": "",
      "hiragana": "",
      "example": " Customers can manage their subscription preferences online.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280421,
      "lang": "en"
    },
    {
      "word": "Renovate",
      "meaning": "Cải tạo, nâng cấp",
      "romaji": "",
      "hiragana": "",
      "example": " The company is planning to renovate the office building next month.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280422,
      "lang": "en"
    },
    {
      "word": "Upcoming",
      "meaning": "Sắp tới, sắp diễn ra",
      "romaji": "",
      "hiragana": "",
      "example": " The upcoming meeting will discuss the quarterly results.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280423,
      "lang": "en"
    },
    {
      "word": "Agenda",
      "meaning": "Chương trình nghị sự",
      "romaji": "",
      "hiragana": "",
      "example": " The agenda for the meeting includes budget review and project updates.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280424,
      "lang": "en"
    }
  ],
  "w1-d2-t1": [
    { "word": "Accept", "meaning": "Chấp nhận", "example": "They decided to accept the offer.", "type": "v", "key": 2000000000001, "lang": "en" },
    { "word": "Achieve", "meaning": "Đạt được", "example": "We aim to achieve our sales target.", "type": "v", "key": 2000000000002, "lang": "en" },
    { "word": "Add", "meaning": "Thêm vào", "example": "Please add these figures to the report.", "type": "v", "key": 2000000000003, "lang": "en" },
    { "word": "Adjust", "meaning": "Điều chỉnh", "example": "You can adjust the volume using this knob.", "type": "v", "key": 2000000000004, "lang": "en" },
    { "word": "Admit", "meaning": "Thừa nhận", "example": "He admitted his mistake during the meeting.", "type": "v", "key": 2000000000005, "lang": "en" },
    { "word": "Advise", "meaning": "Khuyên bảo", "example": "I strongly advise you to check the contract.", "type": "v", "key": 2000000000006, "lang": "en" },
    { "word": "Afford", "meaning": "Có đủ khả năng, điều kiện", "example": "We cannot afford to lose this client.", "type": "v", "key": 2000000000007, "lang": "en" },
    { "word": "Agree", "meaning": "Đồng ý", "example": "All members agreed with the proposal.", "type": "v", "key": 2000000000008, "lang": "en" },
    { "word": "Allow", "meaning": "Cho phép", "example": "Smoking is not allowed in this building.", "type": "v", "key": 2000000000009, "lang": "en" },
    { "word": "Analyze", "meaning": "Phân tích", "example": "We need to analyze the market trends.", "type": "v", "key": 2000000000010, "lang": "en" },
    { "word": "Announce", "meaning": "Thông báo", "example": "The CEO will announce the new policy tomorrow.", "type": "v", "key": 2000000000011, "lang": "en" },
    { "word": "Apologize", "meaning": "Xin lỗi", "example": "I apologize for the delay in shipping.", "type": "v", "key": 2000000000012, "lang": "en" },
    { "word": "Appear", "meaning": "Xuất hiện, có vẻ", "example": "The project appears to be moving smoothly.", "type": "v", "key": 2000000000013, "lang": "en" },
    { "word": "Apply", "meaning": "Ứng tuyển, áp dụng", "example": "She applied for a job in marketing.", "type": "v", "key": 2000000000014, "lang": "en" },
    { "word": "Appoint", "meaning": "Bổ nhiệm", "example": "They will appoint a new manager soon.", "type": "v", "key": 2000000000015, "lang": "en" },
    { "word": "Approve", "meaning": "Phê duyệt", "example": "The board approved the budget for next year.", "type": "v", "key": 2000000000016, "lang": "en" },
    { "word": "Arrange", "meaning": "Sắp xếp", "example": "Can you arrange a meeting for tomorrow?", "type": "v", "key": 2000000000017, "lang": "en" },
    { "word": "Arrive", "meaning": "Đến", "example": "The train will arrive at platform 4.", "type": "v", "key": 2000000000018, "lang": "en" },
    { "word": "Assist", "meaning": "Hỗ trợ", "example": "Our staff will assist you with your luggage.", "type": "v", "key": 2000000000019, "lang": "en" },
    { "word": "Assume", "meaning": "Cho rằng, đảm đương", "example": "I assume the report is finished.", "type": "v", "key": 2000000000020, "lang": "en" },
    { "word": "Attach", "meaning": "Đính kèm", "example": "Please find the file attached to this email.", "type": "v", "key": 2000000000021, "lang": "en" },
    { "word": "Attend", "meaning": "Tham dự", "example": "Everyone is required to attend the training.", "type": "v", "key": 2000000000022, "lang": "en" },
    { "word": "Attract", "meaning": "Thu hút", "example": "The advertisement attracted many customers.", "type": "v", "key": 2000000000023, "lang": "en" },
    { "word": "Avoid", "meaning": "Tránh", "example": "We should avoid making the same mistakes.", "type": "v", "key": 2000000000024, "lang": "en" },
    { "word": "Award", "meaning": "Trao thưởng", "example": "The company was awarded the top prize.", "type": "v", "key": 2000000000025, "lang": "en" }
  ],
  "w1-d3-t1": [
    { "word": "Absolute", "meaning": "Tuyệt đối", "example": "I have absolute confidence in our team.", "type": "adj", "key": 3000000000001, "lang": "en" },
    { "word": "Accurate", "meaning": "Chính xác", "example": "Please ensure the financial data is accurate.", "type": "adj", "key": 3000000000002, "lang": "en" },
    { "word": "Active", "meaning": "Năng động, hoạt động", "example": "He is an active member of our association.", "type": "adj", "key": 3000000000003, "lang": "en" },
    { "word": "Additional", "meaning": "Bổ sung, thêm vào", "example": "There will be an additional charge for delivery.", "type": "adj", "key": 3000000000004, "lang": "en" },
    { "word": "Adequate", "meaning": "Đầy đủ, tương xứng", "example": "Make sure we have adequate supplies.", "type": "adj", "key": 3000000000005, "lang": "en" },
    { "word": "Annual", "meaning": "Hàng năm", "example": "We held our annual general meeting yesterday.", "type": "adj", "key": 3000000000006, "lang": "en" },
    { "word": "Appropriate", "meaning": "Phù hợp, thích hợp", "example": "Please wear appropriate clothing to the office.", "type": "adj", "key": 3000000000007, "lang": "en" },
    { "word": "Available", "meaning": "Có sẵn, rảnh", "example": "The manager is not available at the moment.", "type": "adj", "key": 3000000000008, "lang": "en" },
    { "word": "Basic", "meaning": "Cơ bản", "example": "They offer a basic salary plus commission.", "type": "adj", "key": 3000000000009, "lang": "en" },
    { "word": "Beneficial", "meaning": "Có lợi", "example": "This agreement will be beneficial to both parties.", "type": "adj", "key": 3000000000010, "lang": "en" },
    { "word": "Careful", "meaning": "Cẩn thận", "example": "Be careful when handling the fragile items.", "type": "adj", "key": 3000000000011, "lang": "en" },
    { "word": "Certain", "meaning": "Chắc chắn", "example": "I am certain that the project will succeed.", "type": "adj", "key": 3000000000012, "lang": "en" },
    { "word": "Clear", "meaning": "Rõ ràng", "example": "The instructions were very clear and easy to follow.", "type": "adj", "key": 3000000000013, "lang": "en" },
    { "word": "Common", "meaning": "Phổ biến, chung", "example": "This is a common problem in the industry.", "type": "adj", "key": 3000000000014, "lang": "en" },
    { "word": "Competitive", "meaning": "Cạnh tranh", "example": "We offer highly competitive prices.", "type": "adj", "key": 3000000000015, "lang": "en" },
    { "word": "Complete", "meaning": "Trọn vẹn, đầy đủ", "example": "Please return the complete form by tomorrow.", "type": "adj", "key": 3000000000016, "lang": "en" },
    { "word": "Complex", "meaning": "Phức tạp", "example": "The software is designed to solve complex problems.", "type": "adj", "key": 3000000000017, "lang": "en" },
    { "word": "Confident", "meaning": "Tự tin", "example": "We are confident that we will win the trial.", "type": "adj", "key": 3000000000018, "lang": "en" },
    { "word": "Convenient", "meaning": "Tiện lợi, thuận tiện", "example": "Our hotel is located in a convenient area.", "type": "adj", "key": 3000000000019, "lang": "en" },
    { "word": "Critical", "meaning": "Quan trọng, phê phán", "example": "Timing is critical for this marketing campaign.", "type": "adj", "key": 3000000000020, "lang": "en" },
    { "word": "Current", "meaning": "Hiện tại", "example": "Under the current system, things are less efficient.", "type": "adj", "key": 3000000000021, "lang": "en" },
    { "word": "Daily", "meaning": "Hàng ngày", "example": "Please submit your daily reports by 5 PM.", "type": "adj", "key": 3000000000022, "lang": "en" },
    { "word": "Difficult", "meaning": "Khó khăn", "example": "It was a difficult decision to make.", "type": "adj", "key": 3000000000023, "lang": "en" },
    { "word": "Direct", "meaning": "Trực tiếp", "example": "Please speak in a direct manner.", "type": "adj", "key": 3000000000024, "lang": "en" },
    { "word": "Effective", "meaning": "Hiệu quả", "example": "This medicine is highly effective.", "type": "adj", "key": 3000000000025, "lang": "en" }
  ],
  "w1-d4-t1": [
    { "word": "Account", "meaning": "Tài khoản, khách hàng", "example": "Please open a new account for this client.", "type": "n", "key": 4000000000001, "lang": "en" },
    { "word": "Agreement", "meaning": "Sự thỏa thuận, hợp đồng", "example": "We have reached an agreement on the terms.", "type": "n", "key": 4000000000002, "lang": "en" },
    { "word": "Benefit", "meaning": "Lợi ích, phúc lợi", "example": "The company offers great employee benefits.", "type": "n", "key": 4000000000003, "lang": "en" },
    { "word": "Board", "meaning": "Ban giám đốc, bảng", "example": "The board of directors will meet tomorrow.", "type": "n", "key": 4000000000004, "lang": "en" },
    { "word": "Budget", "meaning": "Ngân sách", "example": "We must stay within the annual budget.", "type": "n", "key": 4000000000005, "lang": "en" },
    { "word": "Candidate", "meaning": "Ứng cử viên", "example": "She is the strongest candidate for the job.", "type": "n", "key": 4000000000006, "lang": "en" },
    { "word": "Client", "meaning": "Khách hàng", "example": "Our clients are very satisfied with the service.", "type": "n", "key": 4000000000007, "lang": "en" },
    { "word": "Committee", "meaning": "Ủy ban", "example": "The committee will review your application.", "type": "n", "key": 4000000000008, "lang": "en" },
    { "word": "Contract", "meaning": "Hợp đồng", "example": "He signed the contract yesterday.", "type": "n", "key": 4000000000009, "lang": "en" },
    { "word": "Cost", "meaning": "Chi phí", "example": "The cost of living has gone up.", "type": "n", "key": 4000000000010, "lang": "en" },
    { "word": "Customer", "meaning": "Khách hàng", "example": "The customer is always right.", "type": "n", "key": 4000000000011, "lang": "en" },
    { "word": "Deadline", "meaning": "Hạn chót", "example": "We need to meet the deadline by Friday.", "type": "n", "key": 4000000000012, "lang": "en" },
    { "word": "Department", "meaning": "Bộ phận, phòng ban", "example": "He transferred to the sales department.", "type": "n", "key": 4000000000013, "lang": "en" },
    { "word": "Detail", "meaning": "Chi tiết", "example": "Please pay attention to every detail.", "type": "n", "key": 4000000000014, "lang": "en" },
    { "word": "Director", "meaning": "Giám đốc, người quản lý", "example": "The director approved the new proposal.", "type": "n", "key": 4000000000015, "lang": "en" },
    { "word": "Employee", "meaning": "Nhân viên", "example": "Every employee receives annual training.", "type": "n", "key": 4000000000016, "lang": "en" },
    { "word": "Equipment", "meaning": "Trang thiết bị", "example": "We bought new equipment for the factory.", "type": "n", "key": 4000000000017, "lang": "en" },
    { "word": "Event", "meaning": "Sự kiện", "example": "The corporate event was a huge success.", "type": "n", "key": 4000000000018, "lang": "en" },
    { "word": "Experience", "meaning": "Kinh nghiệm, trải nghiệm", "example": "She has ten years of experience in sales.", "type": "n", "key": 4000000000019, "lang": "en" },
    { "word": "Facility", "meaning": "Cơ sở, hạ tầng", "example": "The new facility is fully equipped.", "type": "n", "key": 4000000000020, "lang": "en" },
    { "word": "Feedback", "meaning": "Phản hồi", "example": "We appreciate your honest feedback.", "type": "n", "key": 4000000000021, "lang": "en" },
    { "word": "Goal", "meaning": "Mục tiêu", "example": "Our ultimate goal is customer satisfaction.", "type": "n", "key": 4000000000022, "lang": "en" },
    { "word": "Interview", "meaning": "Cuộc phỏng vấn", "example": "I have a job interview tomorrow morning.", "type": "n", "key": 4000000000023, "lang": "en" },
    { "word": "Issue", "meaning": "Vấn đề", "example": "We need to resolve this issue quickly.", "type": "n", "key": 4000000000024, "lang": "en" },
    { "word": "Item", "meaning": "Món đồ, đề mục", "example": "There is a new item on the menu.", "type": "n", "key": 4000000000025, "lang": "en" }
  ]
};
