export const VOCAB_TASKS = {
  "w1-d1-t3": [
    {
      "word": "Representative",
      "meaning": "Người đại diện",
      "romaji": "",
      "hiragana": "The representative from the sales department will assist you.",
      "example": "",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280400,
      "lang": "en"
    },
    {
      "word": "Significant",
      "meaning": "Đáng kể, quan trọng",
      "romaji": "",
      "hiragana": "",
      "example": " A significant increase in sales was observed last quarter.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280401,
      "lang": "en"
    },
    {
      "word": "Negotiate",
      "meaning": "Đàm phán, thương lượng",
      "romaji": "",
      "hiragana": "",
      "example": " We need to negotiate the terms of the contract before signing.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280402,
      "lang": "en"
    },
    {
      "word": "Policy",
      "meaning": "Chính sách",
      "romaji": "",
      "hiragana": "",
      "example": " The company's return policy allows customers to return products within 30 days.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280403,
      "lang": "en"
    },
    {
      "word": "Available",
      "meaning": "Có sẵn, rảnh rỗi",
      "romaji": "",
      "hiragana": "",
      "example": " These products are available in our store.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280404,
      "lang": "en"
    },
    {
      "word": "Implement",
      "meaning": "Thi hành, thực hiện",
      "romaji": "",
      "hiragana": "",
      "example": " The company plans to implement the new software next month.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280405,
      "lang": "en"
    },
    {
      "word": "Candidate",
      "meaning": "Ứng viên",
      "romaji": "",
      "hiragana": "",
      "example": " The candidate has an impressive resume and relevant experience.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280406,
      "lang": "en"
    },
    {
      "word": "Exceed",
      "meaning": "Vượt quá, phóng đại",
      "romaji": "",
      "hiragana": "",
      "example": " The sales exceeded our expectations this quarter.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280407,
      "lang": "en"
    },
    {
      "word": "Productivity",
      "meaning": "Năng suất",
      "romaji": "",
      "hiragana": "",
      "example": " Productivity has increased significantly this year.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280408,
      "lang": "en"
    },
    {
      "word": "Promptly",
      "meaning": "Ngay lập tức, đúng giờ",
      "romaji": "",
      "hiragana": "",
      "example": " The meeting started promptly at 9 AM.",
      "katakana": "",
      "type": "adv",
      "ipa": "",
      "key": 1770134280409,
      "lang": "en"
    },
    {
      "word": "Inspection",
      "meaning": "Sự kiểm tra, thanh tra",
      "romaji": "",
      "hiragana": "",
      "example": " The inspection revealed several safety violations.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280410,
      "lang": "en"
    },
    {
      "word": "Merchandise",
      "meaning": "Hàng hóa (thương mại)",
      "romaji": "",
      "hiragana": "",
      "example": " The store offers a wide range of merchandise for customers.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280411,
      "lang": "en"
    },
    {
      "word": "Strictly",
      "meaning": "Một cách nghiêm ngặt",
      "romaji": "",
      "hiragana": "",
      "example": " The company enforces its policies strictly to ensure compliance.",
      "katakana": "",
      "type": "adv",
      "ipa": "",
      "key": 1770134280412,
      "lang": "en"
    },
    {
      "word": "Promote",
      "meaning": "Thăng chức, quảng bá",
      "romaji": "",
      "hiragana": "",
      "example": " The company promotes employees based on their performance and dedication.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280413,
      "lang": "en"
    },
    {
      "word": "Replacement",
      "meaning": "Sự thay thế, người thay thế",
      "romaji": "",
      "hiragana": "",
      "example": " The company has hired a replacement for the vacant position.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280414,
      "lang": "en"
    },
    {
      "word": "Tentative",
      "meaning": "Dự kiến, không chắc chắn",
      "romaji": "",
      "hiragana": "",
      "example": " The tentative schedule is subject to change based on project requirements.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280415,
      "lang": "en"
    },
    {
      "word": "Reimburse",
      "meaning": "Hoàn lại tiền",
      "romaji": "",
      "hiragana": "",
      "example": " Employees will be reimbursed for travel expenses.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280416,
      "lang": "en"
    },
    {
      "word": "Eligible",
      "meaning": "Đủ tư cách, thích hợp",
      "romaji": "",
      "hiragana": "",
      "example": " Employees must meet the eligibility criteria to participate in the program.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280417,
      "lang": "en"
    },
    {
      "word": "Inquiry",
      "meaning": "Câu hỏi, sự thắc mắc",
      "romaji": "",
      "hiragana": "",
      "example": " Customers can contact the inquiry department for more information.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280418,
      "lang": "en"
    },
    {
      "word": "Announce",
      "meaning": "Thông báo, công bố",
      "romaji": "",
      "hiragana": "",
      "example": " The company announced a new product launch next month.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280419,
      "lang": "en"
    },
    {
      "word": "Mandatory",
      "meaning": "Bắt buộc",
      "romaji": "",
      "hiragana": "",
      "example": " Attendance at the training session is mandatory for all employees.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280420,
      "lang": "en"
    },
    {
      "word": "Subscription",
      "meaning": "Sự đăng ký, thuê bao",
      "romaji": "",
      "hiragana": "",
      "example": " Customers can manage their subscription preferences online.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280421,
      "lang": "en"
    },
    {
      "word": "Renovate",
      "meaning": "Cải tạo, nâng cấp",
      "romaji": "",
      "hiragana": "",
      "example": " The company is planning to renovate the office building next month.",
      "katakana": "",
      "type": "v",
      "ipa": "",
      "key": 1770134280422,
      "lang": "en"
    },
    {
      "word": "Upcoming",
      "meaning": "Sắp tới, sắp diễn ra",
      "romaji": "",
      "hiragana": "",
      "example": " The upcoming meeting will discuss the quarterly results.",
      "katakana": "",
      "type": "adj",
      "ipa": "",
      "key": 1770134280423,
      "lang": "en"
    },
    {
      "word": "Agenda",
      "meaning": "Chương trình nghị sự",
      "romaji": "",
      "hiragana": "",
      "example": " The agenda for the meeting includes budget review and project updates.",
      "katakana": "",
      "type": "n",
      "ipa": "",
      "key": 1770134280424,
      "lang": "en"
    }
]
};
